// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: peer.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RequestVoteArgs struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId          int32    `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex         int64    `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm          int64    `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteArgs) Reset()         { *m = RequestVoteArgs{} }
func (m *RequestVoteArgs) String() string { return proto.CompactTextString(m) }
func (*RequestVoteArgs) ProtoMessage()    {}
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{0}
}
func (m *RequestVoteArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteArgs.Unmarshal(m, b)
}
func (m *RequestVoteArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteArgs.Marshal(b, m, deterministic)
}
func (m *RequestVoteArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteArgs.Merge(m, src)
}
func (m *RequestVoteArgs) XXX_Size() int {
	return xxx_messageInfo_RequestVoteArgs.Size(m)
}
func (m *RequestVoteArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteArgs proto.InternalMessageInfo

func (m *RequestVoteArgs) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteArgs) GetCandidateId() int32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteArgs) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteArgs) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteReply) Reset()         { *m = RequestVoteReply{} }
func (m *RequestVoteReply) String() string { return proto.CompactTextString(m) }
func (*RequestVoteReply) ProtoMessage()    {}
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{1}
}
func (m *RequestVoteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteReply.Unmarshal(m, b)
}
func (m *RequestVoteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteReply.Marshal(b, m, deterministic)
}
func (m *RequestVoteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteReply.Merge(m, src)
}
func (m *RequestVoteReply) XXX_Size() int {
	return xxx_messageInfo_RequestVoteReply.Size(m)
}
func (m *RequestVoteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteReply proto.InternalMessageInfo

func (m *RequestVoteReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReply) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type AppendEntryArgs struct {
	Term     int32 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId int32 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// Entries			[]Entry // new data to sync
	PrevLogIndex         int64    `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm          int64    `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	LeaderCommit         int64    `protobuf:"varint,5,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryArgs) Reset()         { *m = AppendEntryArgs{} }
func (m *AppendEntryArgs) String() string { return proto.CompactTextString(m) }
func (*AppendEntryArgs) ProtoMessage()    {}
func (*AppendEntryArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{2}
}
func (m *AppendEntryArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryArgs.Unmarshal(m, b)
}
func (m *AppendEntryArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryArgs.Marshal(b, m, deterministic)
}
func (m *AppendEntryArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryArgs.Merge(m, src)
}
func (m *AppendEntryArgs) XXX_Size() int {
	return xxx_messageInfo_AppendEntryArgs.Size(m)
}
func (m *AppendEntryArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryArgs proto.InternalMessageInfo

func (m *AppendEntryArgs) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryArgs) GetLeaderId() int32 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntryArgs) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntryArgs) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntryArgs) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntryReply struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ConflictIndex        int64    `protobuf:"varint,3,opt,name=ConflictIndex,proto3" json:"ConflictIndex,omitempty"`
	ConflictTerm         int64    `protobuf:"varint,4,opt,name=ConflictTerm,proto3" json:"ConflictTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryReply) Reset()         { *m = AppendEntryReply{} }
func (m *AppendEntryReply) String() string { return proto.CompactTextString(m) }
func (*AppendEntryReply) ProtoMessage()    {}
func (*AppendEntryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{3}
}
func (m *AppendEntryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryReply.Unmarshal(m, b)
}
func (m *AppendEntryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryReply.Marshal(b, m, deterministic)
}
func (m *AppendEntryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryReply.Merge(m, src)
}
func (m *AppendEntryReply) XXX_Size() int {
	return xxx_messageInfo_AppendEntryReply.Size(m)
}
func (m *AppendEntryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryReply proto.InternalMessageInfo

func (m *AppendEntryReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntryReply) GetConflictIndex() int64 {
	if m != nil {
		return m.ConflictIndex
	}
	return 0
}

func (m *AppendEntryReply) GetConflictTerm() int64 {
	if m != nil {
		return m.ConflictTerm
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestVoteArgs)(nil), "proto.RequestVoteArgs")
	proto.RegisterType((*RequestVoteReply)(nil), "proto.RequestVoteReply")
	proto.RegisterType((*AppendEntryArgs)(nil), "proto.AppendEntryArgs")
	proto.RegisterType((*AppendEntryReply)(nil), "proto.AppendEntryReply")
}

func init() { proto.RegisterFile("peer.proto", fileDescriptor_055ae5a865fc1c9e) }

var fileDescriptor_055ae5a865fc1c9e = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0xc2, 0x30,
	0x18, 0x86, 0x53, 0x01, 0x81, 0x6f, 0x20, 0xa4, 0x07, 0x5d, 0xf4, 0x82, 0x93, 0x03, 0x27, 0x0e,
	0x7a, 0x34, 0x21, 0x41, 0x62, 0xcc, 0x12, 0x0f, 0x66, 0x21, 0x1e, 0xbc, 0x2c, 0x73, 0xfd, 0x5c,
	0x96, 0x6c, 0xeb, 0xec, 0x0a, 0x91, 0x3f, 0xe0, 0xc1, 0xa3, 0xff, 0xc4, 0x7f, 0x68, 0xd6, 0x8d,
	0x51, 0x20, 0x3b, 0x75, 0x7b, 0xfa, 0x36, 0x7d, 0x9f, 0xb6, 0x00, 0x29, 0xa2, 0x98, 0xa6, 0x82,
	0x4b, 0x4e, 0x5b, 0x6a, 0xb0, 0x7e, 0x09, 0x0c, 0x1c, 0xfc, 0x5c, 0x61, 0x26, 0x5f, 0xb9, 0xc4,
	0xb9, 0x08, 0x32, 0x4a, 0xa1, 0x29, 0x51, 0xc4, 0x26, 0x19, 0x91, 0x49, 0xcb, 0x51, 0xdf, 0xf4,
	0x1a, 0x7a, 0xbe, 0x97, 0xb0, 0x90, 0x79, 0x12, 0xdd, 0x90, 0x99, 0x27, 0x6a, 0xce, 0xa8, 0x98,
	0xcd, 0xe8, 0x18, 0xce, 0x22, 0x2f, 0x93, 0x6e, 0xc4, 0x03, 0x37, 0x4c, 0x18, 0x7e, 0x99, 0x8d,
	0x11, 0x99, 0x34, 0x9c, 0x5e, 0x4e, 0x9f, 0x79, 0x60, 0xe7, 0x8c, 0x5a, 0xd0, 0xaf, 0x52, 0x6a,
	0x97, 0xa6, 0x0a, 0x19, 0x65, 0x68, 0x89, 0x22, 0xb6, 0x6c, 0x18, 0x6a, 0x9d, 0x1c, 0x4c, 0xa3,
	0x4d, 0x5d, 0xa9, 0x35, 0x97, 0xe8, 0x06, 0xc2, 0x4b, 0x24, 0x16, 0xa5, 0x3a, 0x8e, 0x91, 0xb3,
	0xa7, 0x02, 0x59, 0x7f, 0x04, 0x06, 0xf3, 0x34, 0xc5, 0x84, 0x3d, 0x26, 0x52, 0x6c, 0x6a, 0xfd,
	0xae, 0xa0, 0x1b, 0xa1, 0xc7, 0x50, 0xec, 0xe4, 0x3a, 0x05, 0x28, 0xcc, 0x52, 0x81, 0xeb, 0x63,
	0xb3, 0x9c, 0xea, 0x66, 0x55, 0x4a, 0x37, 0x2b, 0x43, 0xb9, 0x19, 0xbd, 0x81, 0x7e, 0xb9, 0x8d,
	0xcf, 0xe3, 0x38, 0x94, 0x66, 0xab, 0x3c, 0x22, 0x05, 0x17, 0x8a, 0x59, 0x3f, 0x04, 0x86, 0x5a,
	0xe7, 0x7a, 0x7f, 0x13, 0xda, 0xd9, 0xca, 0xf7, 0x31, 0xcb, 0x4a, 0xf5, 0xed, 0x2f, 0x1d, 0x43,
	0x7f, 0xc1, 0x93, 0x8f, 0x28, 0xf4, 0xa5, 0xad, 0x15, 0xde, 0x87, 0xd4, 0x82, 0xde, 0x16, 0x2c,
	0x77, 0x85, 0xf7, 0xd8, 0xed, 0x37, 0x81, 0xe6, 0x0b, 0xa2, 0xa0, 0x33, 0x30, 0xb4, 0x4b, 0xa1,
	0xe7, 0xc5, 0x3b, 0x9a, 0x1e, 0x3c, 0x9e, 0xcb, 0x8b, 0x63, 0x5e, 0x08, 0xcc, 0xc0, 0xd0, 0xa4,
	0xaa, 0xf5, 0x07, 0x97, 0x53, 0xad, 0x3f, 0x3c, 0x80, 0x87, 0xee, 0x5b, 0x7b, 0x7a, 0xaf, 0xe6,
	0xde, 0x4f, 0xd5, 0x70, 0xf7, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x0d, 0xd4, 0xe8, 0xd0, 0x02,
	0x00, 0x00,
}
